version: '3.8'
services:
  bolt:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
      - PORT=5173
      - RUNNING_IN_DOCKER=true
      - NODE_OPTIONS=--max_old_space_size=8192 --expose-gc
      - GROQ_API_KEY=${GROQ_API_KEY}
      - HuggingFace_API_KEY=${HuggingFace_API_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - OPEN_ROUTER_API_KEY=${OPEN_ROUTER_API_KEY}
      - GOOGLE_GENERATIVE_AI_API_KEY=${GOOGLE_GENERATIVE_AI_API_KEY}
      - OLLAMA_API_BASE_URL=${OLLAMA_API_BASE_URL:-http://ollama:11434}
      - XAI_API_KEY=${XAI_API_KEY}
      - TOGETHER_API_KEY=${TOGETHER_API_KEY}
      - TOGETHER_API_BASE_URL=${TOGETHER_API_BASE_URL}
      - AWS_BEDROCK_CONFIG=${AWS_BEDROCK_CONFIG}
      - DEFAULT_NUM_CTX=${DEFAULT_NUM_CTX:-32768}
      - VITE_CJS_IGNORE_WARNING=true
      - VITE_CJS_TRACE=true
      - HOST=0.0.0.0
      - VITE_LOG_LEVEL=debug
      - WRANGLER_SEND_METRICS=false
    expose:
      - "5173"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--spider", "http://localhost:5173"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
networks:
  default:
    name: coolify-${COOLIFY_RESOURCE_UUID}
    external: true